#! /bin/bash

#root privilege
if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi
apt-get install libcunit1 libcunit1-doc libcunit1-dev
ANSW=""
#g++ main.cpp -o main -pthread -lcunit to compile
read -p "Do you want to compile? (yes/anything else) : " ANSW
if [[ $ANSW == "yes" ]]
then
	g++ main.cpp -o main -pthread -lcunit
else
	echo "OK!"
	exit
fi	
exit


